### PR TITLE
Better Doc

### PR DESCRIPTION
**Pull request by KwikKill**
Update Readme
Add Pull request template

### CODE REVIEW

**Review by Lugrim — APPROVED** [review]
Good, clean project management is satisfying to see

**Review by ShiroUsagi-san — COMMENTED** [review]
Adding a part about configuring IDE to be compliant with our linting rules?

**Comment by Dyskal** [comment]
isnt it just eslint and editorconfig?

**Comment by KwikKill** [comment]
> Adding a part about configuring IDE to be compliant with our linting rules?

We could but the problem is that the configuration is already done and having your IDE using it depends on the IDE and the env (Linux, WSL2,...). I'll try later adding this but it's easier to check with everyone for now.

**Pull request merged**
