### PR TITLE
QR Code scan page

### PR DESCRIPTION
**Pull request by Dyskal**
First version of the ticket scanning, able to scan, verify and validate a ticket

### CODE REVIEW

**Review by KwikKill — COMMENTED** [review]
We are almost there, we only miss one feature, being able to mark as paid a registration after a player paid on site. We need a search bar for username to search in valid unpaid registrations. This account list can be found in the tournament store by filtering teams (only validated) and registrations (only unpaid or pay later).

This require an admin endpoint (by registration id) that set the payment to paid, create a ticket (for the next day) and send it by mail.

**Review by ShiroUsagi-san — APPROVED** [review]
This looks good to me

**Comment by KwikKill** [comment]
We also need to show more data on screen. We need at least first and last name (when present), tournament / game and team.

**Comment by KwikKill** [comment]
Last commit added a button to set a registration to paid if the user is paying on site.
image

**Pull request merged**
